[package]
name = "winn"
version = "0.1.0"
edition = "2024"




[dependencies]
winapi = { version = "0.3", features = ["winuser", "dbt", "libloaderapi"] }
widestring = "0.4"

[dependencies.windows]
version = "0.52"
features = [
    "Win32_Foundation",
    "Win32_System_Threading",
]
